### ISSUE TITLE
Viewing Shows - expanded TO THINK ABOUT LATER...

### ISSUE THREAD

**Issue by ericfitzsimons451** [jarushford/plenty-of-phish#15]
Should each set of songs be their own component?

Also, should each song itself be its own component?

**Comment by thatPamIAm** [comment]
@ericfitzsimons451 I definitely think you could break this apart this way if you are displaying it as such. Very similar to our trivia app we built out yesterday - we had a containing component (TriviaList) that was holding our Question component for each individual question. Makes sense to me!
